# Generated by Django 2.2.4 on 2019-10-09 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('risk', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('csr', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('Female_exec', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('hr', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=5)),
                ('industry', models.ManyToManyField(to='recommendation.Industry')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('Female_exec', models.BooleanField()),
                ('risk', models.BooleanField()),
                ('csr', models.BooleanField()),
                ('hr', models.BooleanField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Industry')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Sector')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('questionnaire', models.ForeignKey(null=True, on_delete=False, to='recommendation.Questionnaire')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_recommendations', to='recommendation.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sector',
            field=models.ManyToManyField(to='recommendation.Sector'),
        ),
        migrations.AddField(
            model_name='industry',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.Sector'),
        ),
    ]
